# Generated by Django 6.1 on 2026-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="explanation",
            field=models.TextField(verbose_name="Explanation"),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="front_text",
            field=models.TextField(verbose_name="Flash Text"),
        ),
    ]
