# Generated by Django 6.1 on 2026-08-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0002_alter_flashcard_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizhistory",
            name="flashcards_created",
            field=models.BooleanField(default=False),
        ),
    ]
