# Generated by Django 6.1 on 2026-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0003_quizhistory_flashcards_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.CharField(default="", max_length=100),
        ),
    ]
