# Generated by Django 6.1 on 2026-09-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0005_pilotaccesscode"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="source_citation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The passage from the source document this question's facts were drawn from.",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("FAILED_BLOCKED", "Blocked"),
                    ("FAILED_EXHAUSTED", "Failed - Retries Exhausted"),
                    ("FAILED_API_ERROR", "Failed - System Error"),
                ],
                default="PENDING",
                max_length=17,
            ),
        ),
        migrations.CreateModel(
            name="QuizAggregateMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_reason", models.CharField(default="", max_length=40)),
                ("structural_attempts", models.IntegerField(default=0)),
                ("evaluator_attempts", models.IntegerField(default=0)),
                ("correction_occurred", models.BooleanField(default=False)),
                (
                    "guardrail_category",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "safety_category",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("total_time_seconds", models.FloatField(blank=True, null=True)),
                ("total_cost", models.FloatField(default=0.0)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_metrics",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mlflow_trace_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("node_breakdown", models.JSONField(blank=True, default=list)),
                ("structural_feedback", models.TextField(blank=True, default="")),
                ("evaluation_feedback", models.JSONField(blank=True, default=list)),
                ("guardrail_reason", models.TextField(blank=True, default="")),
                ("safety_reason", models.TextField(blank=True, default="")),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_log",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_text", models.TextField()),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_text_record",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
