# Generated by Django 6.1 on 2026-09-11 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0006_question_source_citation_alter_quiz_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("FACTUALLY_INCORRECT", "Factually incorrect"),
                            (
                                "DOESNT_MATCH_SOURCE",
                                "Doesn't match the source material",
                            ),
                            ("INAPPROPRIATE", "Inappropriate content"),
                            (
                                "TECHNICAL_ISSUE",
                                "Technical issue (formatting, broken display, etc.)",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="quizmaker.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="quizmaker.quiz",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "matched_instructions",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("SOMEWHAT", "Somewhat"),
                            ("NO", "No"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        max_length=8,
                    ),
                ),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
