# Generated by Django 6.1 on 2026-09-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0007_quizflag_quizreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizgenerationlog",
            name="node_breakdown",
        ),
        migrations.CreateModel(
            name="QuizNodeCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_id", models.CharField(blank=True, default="", max_length=60)),
                ("agent", models.CharField(max_length=30)),
                ("model", models.CharField(blank=True, default="", max_length=60)),
                ("cost", models.FloatField(default=0.0)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_costs",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
