# Generated by Django 6.1 on 2026-09-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0008_remove_quizgenerationlog_node_breakdown_quiznodecost"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiznodecost",
            name="input_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="quiznodecost",
            name="output_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
