# Generated by Django 6.1 on 2026-09-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0009_quiznodecost_input_cost_quiznodecost_output_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiznodecost",
            name="duration_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
