# Generated by Django 6.1 on 2026-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0010_quiznodecost_duration_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="exam_name",
            field=models.CharField(
                choices=[
                    ("UPSC", "UPSC Prelims"),
                    ("GENERAL", "General Knowledge"),
                    ("AI_ML", "AI / Machine Learning"),
                    ("INTERVIEW_PREP", "Interview Preparation"),
                    ("GRADE_12_BELOW", "12th Grade and Below"),
                ],
                default="UPSC",
                max_length=20,
            ),
        ),
    ]
