# Generated by Django 6.1 on 2026-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0011_alter_quiz_exam_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="hint",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="question",
            name="hint",
            field=models.TextField(default=""),
        ),
    ]
