# Generated by Django 6.1 on 2026-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0012_alter_flashcard_hint_alter_question_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizgenerationlog",
            name="thread_id",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
