# Generated by Django 6.1 on 2026-09-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0013_quizgenerationlog_thread_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizgenerationlog",
            name="mlflow_trace_id",
        ),
        migrations.RemoveField(
            model_name="quizgenerationlog",
            name="thread_id",
        ),
        migrations.CreateModel(
            name="QuizTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_id", models.CharField(max_length=60)),
                ("mlflow_trace_id", models.CharField(max_length=100)),
                ("crashed", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz", "mlflow_trace_id")},
            },
        ),
    ]
