# Generated by Django 6.1 on 2026-09-16 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "quizmaker",
            "0015_flashcard_correct_streak_flashcard_last_reviewed_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pib_release_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("title_slug", models.CharField(db_index=True, max_length=60)),
                (
                    "issuing_authority",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("source_url", models.URLField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("raw_text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("digest_date", models.DateField(unique=True)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "quiz",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_digest",
                        to="quizmaker.quiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
