# Generated by Django 6.1 on 2026-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0016_newsarticle_dailydigest"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="digest_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="filter_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
