# Generated by Django 6.1 on 2026-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0017_newsarticle_digest_included_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.TextField(),
        ),
    ]
