# Generated by Django 6.1 on 2026-09-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0018_alter_newsarticle_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigestAggregateMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=6, max_digits=10)),
                ("total_calls", models.IntegerField(default=0)),
                ("groups_approved", models.IntegerField(default=0)),
                ("groups_exhausted", models.IntegerField(default=0)),
                ("total_time_seconds", models.FloatField()),
                (
                    "digest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="quizmaker.dailydigest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigestNodeCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=50)),
                ("attempt", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "digest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_costs",
                        to="quizmaker.dailydigest",
                    ),
                ),
            ],
        ),
    ]
