# Generated by Django 6.1 on 2026-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0019_digestaggregatemetrics_digestnodecost"),
    ]

    operations = [
        migrations.AddField(
            model_name="digestaggregatemetrics",
            name="run_log",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
