# Generated by Django 6.1 on 2026-09-19 05:15

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0020_digestaggregatemetrics_run_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("header", models.CharField(blank=True, default="", max_length=255)),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[("prose", "Prose"), ("table", "Table")],
                        default="prose",
                        max_length=10,
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "source_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="quizmaker.sourcetext",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_chunks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="source_chunk_embedding_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
