# Generated by Django 6.1 on 2026-09-19 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0021_sourcechunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicsPreviewBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[("up", "Thumbs Up"), ("down", "Thumbs Down")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics_previews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wrong_answers_covered",
                    models.ManyToManyField(
                        related_name="covered_in_briefs",
                        to="quizmaker.quizattemptanswer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
