# Generated by Django 6.1 on 2026-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0022_topicspreviewbrief"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicspreviewbrief",
            name="skipped_questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
