# Generated by Django 6.1 on 2026-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0023_topicspreviewbrief_skipped_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicspreviewbrief",
            name="faithfulness_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
