# Generated by Django 6.1 on 2026-09-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0024_topicspreviewbrief_faithfulness_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicspreviewbrief",
            name="faithfulness_score",
        ),
        migrations.AlterField(
            model_name="topicspreviewbrief",
            name="content",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
