# Generated by Django 6.1 on 2026-09-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizmaker", "0025_remove_topicspreviewbrief_faithfulness_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicsPreviewCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, max_digits=10)),
                ("total_time_seconds", models.FloatField()),
                (
                    "brief",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost",
                        to="quizmaker.topicspreviewbrief",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
